// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGwfybttHLFkU_OifUxK65HyspuE-E8zA',
    appId: '1:522982440335:web:d7ac4b8368c2ebbe9d9ffa',
    messagingSenderId: '522982440335',
    projectId: 'barber-45b35',
    authDomain: 'barber-45b35.firebaseapp.com',
    storageBucket: 'barber-45b35.firebasestorage.app',
    measurementId: 'G-ENXDX5PE4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1SpueSMev9GE9UMAnH8Bo_gsx-VOSBNM',
    appId: '1:522982440335:android:049f68c0e52a95679d9ffa',
    messagingSenderId: '522982440335',
    projectId: 'barber-45b35',
    storageBucket: 'barber-45b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZJd61T87GJ-f7nBR4qBeqAGgqUTfqrfI',
    appId: '1:522982440335:ios:cbaf1332ce6c89859d9ffa',
    messagingSenderId: '522982440335',
    projectId: 'barber-45b35',
    storageBucket: 'barber-45b35.firebasestorage.app',
    iosBundleId: 'com.example.barberShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZJd61T87GJ-f7nBR4qBeqAGgqUTfqrfI',
    appId: '1:522982440335:ios:cbaf1332ce6c89859d9ffa',
    messagingSenderId: '522982440335',
    projectId: 'barber-45b35',
    storageBucket: 'barber-45b35.firebasestorage.app',
    iosBundleId: 'com.example.barberShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGwfybttHLFkU_OifUxK65HyspuE-E8zA',
    appId: '1:522982440335:web:87b8aaded7d1c84f9d9ffa',
    messagingSenderId: '522982440335',
    projectId: 'barber-45b35',
    authDomain: 'barber-45b35.firebaseapp.com',
    storageBucket: 'barber-45b35.firebasestorage.app',
    measurementId: 'G-MEMHC56HW3',
  );
}
